{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zzx.pluginhook",
    "module": "pluginhook",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pluginhook-1.0.jar",
          "url": "pluginhook-1.0.jar",
          "size": 25493,
          "sha512": "aee191303ed67001f24e7eeb14a3f2d78ca2fb08a61bcdae4dd5fd3cd0787c22c945bb9d3b82bd2db32b8b86e9013f13f64d93a960120d6956761579de9f1341",
          "sha256": "1a96b58028bfd308e346f9889fbfcf9813400fa2d0995f0ac02f61d67543c448",
          "sha1": "212e9f518ed0e73bb7df660a25d73d36c353b1d7",
          "md5": "642eafb06fb2549469f3a1f6b73ea89d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "pluginhook-1.0.jar",
          "url": "pluginhook-1.0.jar",
          "size": 25493,
          "sha512": "aee191303ed67001f24e7eeb14a3f2d78ca2fb08a61bcdae4dd5fd3cd0787c22c945bb9d3b82bd2db32b8b86e9013f13f64d93a960120d6956761579de9f1341",
          "sha256": "1a96b58028bfd308e346f9889fbfcf9813400fa2d0995f0ac02f61d67543c448",
          "sha1": "212e9f518ed0e73bb7df660a25d73d36c353b1d7",
          "md5": "642eafb06fb2549469f3a1f6b73ea89d"
        }
      ]
    }
  ]
}
