{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zzx.pluginhook",
    "module": "pluginhook",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pluginhook-1.0.jar",
          "url": "pluginhook-1.0.jar",
          "size": 25484,
          "sha512": "e74e1f696338e94a43c3f04b09b777628ab4e1b74b98225c5aea084dc42c6d6ea0ab48df692af945703fe3bf0a3b25b8d85bcaf9ce53a41408d3a9e1d8eb301c",
          "sha256": "024a587885ae3b7937da74ca3d257fd726eb1976a4788e66690866147571b330",
          "sha1": "7e34f3495126631580cc7c24ecbf62dc211ea064",
          "md5": "4e5ce50f24a7098b253cee507505e256"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "pluginhook-1.0.jar",
          "url": "pluginhook-1.0.jar",
          "size": 25484,
          "sha512": "e74e1f696338e94a43c3f04b09b777628ab4e1b74b98225c5aea084dc42c6d6ea0ab48df692af945703fe3bf0a3b25b8d85bcaf9ce53a41408d3a9e1d8eb301c",
          "sha256": "024a587885ae3b7937da74ca3d257fd726eb1976a4788e66690866147571b330",
          "sha1": "7e34f3495126631580cc7c24ecbf62dc211ea064",
          "md5": "4e5ce50f24a7098b253cee507505e256"
        }
      ]
    }
  ]
}
